version: '3.7'
services:
  mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  backend:
    image: doodle-api:latest
    ports:
      - 8080:8080

volumes:
  mongodb_data_container:
